### ISSUE TITLE
can you make it a minimal runnning git？

### ISSUE THREAD

**Issue by wentixiaogege** [omar-elmaria/switchback_test_dag#1]

**Comment by omar-elmaria** [comment]
Hello @wentixiaogege,

Thanks for raising this issue. As I highlighted in the Readme of the repo, this project was internal and used proprietary data sources and analysis methodologies. Even though you can clone the repo, the results cannot be reproduced on another machine due to data-sharing restrictions. The code will give you an error because you don't have the necessary data access permissions.

If you are interested in knowing more about the framework or leveraging it in a particular use case, please get in touch with me on [LinkedIn](https://www.linkedin.com/in/omar-elmaria/), and we can discuss more.
